apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: software-arch-team4
  labels:
    app.kubernetes.io/name: software_arch_team_4
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Uses cluster default StorageClass (local-path on k3d).
