apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: software-arch-team4
resources:
  - ../full
  - ../../../haproxy
  - haproxy-deployment.yaml
  - haproxy-service.yaml
patches:
  - target:
      kind: ConfigMap
      name: app-config
    patch: |-
      - op: add
        path: /data/SERVE_STATIC
        value: "true"
