apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: software-arch-team4
  labels:
    app: mongodb
    app.kubernetes.io/name: software_arch_team_4
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP
